// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/baetyl/baetyl-cloud/v2/plugin/kube/apis/cloud/v1alpha1"
	scheme "github.com/baetyl/baetyl-cloud/v2/plugin/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeReportsGetter has a method to return a NodeReportInterface.
// A group's client should implement this interface.
type NodeReportsGetter interface {
	NodeReports(namespace string) NodeReportInterface
}

// NodeReportInterface has methods to work with NodeReport resources.
type NodeReportInterface interface {
	Create(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.CreateOptions) (*v1alpha1.NodeReport, error)
	Update(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.UpdateOptions) (*v1alpha1.NodeReport, error)
	UpdateStatus(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.UpdateOptions) (*v1alpha1.NodeReport, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NodeReport, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NodeReportList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeReport, err error)
	NodeReportExpansion
}

// nodeReports implements NodeReportInterface
type nodeReports struct {
	client rest.Interface
	ns     string
}

// newNodeReports returns a NodeReports
func newNodeReports(c *CloudV1alpha1Client, namespace string) *nodeReports {
	return &nodeReports{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeReport, and returns the corresponding nodeReport object, and an error if there is any.
func (c *nodeReports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeReport, err error) {
	result = &v1alpha1.NodeReport{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodereports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeReports that match those selectors.
func (c *nodeReports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeReportList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NodeReportList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodereports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeReports.
func (c *nodeReports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodereports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeReport and creates it.  Returns the server's representation of the nodeReport, and an error, if there is any.
func (c *nodeReports) Create(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.CreateOptions) (result *v1alpha1.NodeReport, err error) {
	result = &v1alpha1.NodeReport{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodereports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeReport).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeReport and updates it. Returns the server's representation of the nodeReport, and an error, if there is any.
func (c *nodeReports) Update(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.UpdateOptions) (result *v1alpha1.NodeReport, err error) {
	result = &v1alpha1.NodeReport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodereports").
		Name(nodeReport.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeReport).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nodeReports) UpdateStatus(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.UpdateOptions) (result *v1alpha1.NodeReport, err error) {
	result = &v1alpha1.NodeReport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodereports").
		Name(nodeReport.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeReport).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeReport and deletes it. Returns an error if one occurs.
func (c *nodeReports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodereports").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeReports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodereports").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeReport.
func (c *nodeReports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeReport, err error) {
	result = &v1alpha1.NodeReport{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodereports").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
