// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/baetyl/baetyl-cloud/v2/plugin/kube/apis/cloud/v1alpha1"
	scheme "github.com/baetyl/baetyl-cloud/v2/plugin/kube/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeDesiresGetter has a method to return a NodeDesireInterface.
// A group's client should implement this interface.
type NodeDesiresGetter interface {
	NodeDesires(namespace string) NodeDesireInterface
}

// NodeDesireInterface has methods to work with NodeDesire resources.
type NodeDesireInterface interface {
	Create(ctx context.Context, nodeDesire *v1alpha1.NodeDesire, opts v1.CreateOptions) (*v1alpha1.NodeDesire, error)
	Update(ctx context.Context, nodeDesire *v1alpha1.NodeDesire, opts v1.UpdateOptions) (*v1alpha1.NodeDesire, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NodeDesire, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NodeDesireList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDesire, err error)
	NodeDesireExpansion
}

// nodeDesires implements NodeDesireInterface
type nodeDesires struct {
	client rest.Interface
	ns     string
}

// newNodeDesires returns a NodeDesires
func newNodeDesires(c *CloudV1alpha1Client, namespace string) *nodeDesires {
	return &nodeDesires{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeDesire, and returns the corresponding nodeDesire object, and an error if there is any.
func (c *nodeDesires) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeDesire, err error) {
	result = &v1alpha1.NodeDesire{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedesires").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeDesires that match those selectors.
func (c *nodeDesires) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeDesireList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NodeDesireList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedesires").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeDesires.
func (c *nodeDesires) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodedesires").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeDesire and creates it.  Returns the server's representation of the nodeDesire, and an error, if there is any.
func (c *nodeDesires) Create(ctx context.Context, nodeDesire *v1alpha1.NodeDesire, opts v1.CreateOptions) (result *v1alpha1.NodeDesire, err error) {
	result = &v1alpha1.NodeDesire{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodedesires").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDesire).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeDesire and updates it. Returns the server's representation of the nodeDesire, and an error, if there is any.
func (c *nodeDesires) Update(ctx context.Context, nodeDesire *v1alpha1.NodeDesire, opts v1.UpdateOptions) (result *v1alpha1.NodeDesire, err error) {
	result = &v1alpha1.NodeDesire{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodedesires").
		Name(nodeDesire.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDesire).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeDesire and deletes it. Returns an error if one occurs.
func (c *nodeDesires) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedesires").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeDesires) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedesires").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeDesire.
func (c *nodeDesires) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDesire, err error) {
	result = &v1alpha1.NodeDesire{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodedesires").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
