FROM golang:1.21.3 as devel
COPY / /go/src/
RUN cd /go/src/ && make build

FROM busybox:1.36.1
COPY /scripts/native/templates /etc/templates
COPY --from=devel /go/src/output/baetyl-cloud /bin/
ENTRYPOINT ["baetyl-cloud"]
