name: "{{.CoreAppName}}"
namespace: "{{.Namespace}}"
selector: "baetyl-node-name={{.NodeName}}"
labels:
  baetyl-cloud-system: "true"
type: "container"
system: true
services:
  - name: "baetyl-core"
    image: "baetyltechtest/baetyl:git-122bf10"
    replica: 1
    args:
      - "core"
    volumeMounts:
      - name: "core-conf"
        mountPath: "/etc/baetyl"
        readOnly: true
      - name: "node-certs"
        mountPath: "/var/lib/baetyl/node"
      - name: "core-store-path"
        mountPath: "/var/lib/baetyl/store"
      - name: "object-download-path"
        mountPath: "/var/lib/baetyl/objects"
      - name: "host-root-path"
        mountPath: "/var/lib/baetyl/hostpath"
      - name: "app-log-path"
        mountPath: "/var/lib/baetyl/logs"
      - name: "native-app-run-path"
        mountPath: "/var/lib/baetyl/run"
    ports:
      - containerPort: 80
        hostPort: 30050
        protocol: "TCP"
volumes:
  - name: "core-conf"
    config:
      name: "{{.CoreConfName}}"
      version: "{{.CoreConfVersion}}"
  - name: "node-certs"
    secret:
      name: "{{.CoreCertName}}"
      version: "{{.CoreCertVersion}}"
  - name: "core-store-path"
    hostPath:
      path: "/var/lib/baetyl/store"
  - name: "object-download-path"
    hostPath:
      path: "/var/lib/baetyl/objects"
  - name: "host-root-path"
    hostPath:
      path: "/var/lib/baetyl/hostpath"
  - name: "app-log-path"
    hostPath:
      path: "/var/lib/baetyl/logs"
  - name: "native-app-run-path"
    hostPath:
      path: "/var/lib/baetyl/run"
