// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baetyl/baetyl-cloud/v2/api (interfaces: InitAPI)

// Package api is a generated GoMock package.
package api

import (
	common "github.com/baetyl/baetyl-cloud/v2/common"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockInitAPI is a mock of InitAPI interface
type MockInitAPI struct {
	ctrl     *gomock.Controller
	recorder *MockInitAPIMockRecorder
}

// MockInitAPIMockRecorder is the mock recorder for MockInitAPI
type MockInitAPIMockRecorder struct {
	mock *MockInitAPI
}

// NewMockInitAPI creates a new mock instance
func NewMockInitAPI(ctrl *gomock.Controller) *MockInitAPI {
	mock := &MockInitAPI{ctrl: ctrl}
	mock.recorder = &MockInitAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInitAPI) EXPECT() *MockInitAPIMockRecorder {
	return m.recorder
}

// GetResource mocks base method
func (m *MockInitAPI) GetResource(arg0 *common.Context) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResource", arg0)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource
func (mr *MockInitAPIMockRecorder) GetResource(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockInitAPI)(nil).GetResource), arg0)
}
