// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baetyl/baetyl-cloud/v2/service (interfaces: LicenseService)

// Package service is a generated GoMock package.
package service

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLicenseService is a mock of LicenseService interface
type MockLicenseService struct {
	ctrl     *gomock.Controller
	recorder *MockLicenseServiceMockRecorder
}

// MockLicenseServiceMockRecorder is the mock recorder for MockLicenseService
type MockLicenseServiceMockRecorder struct {
	mock *MockLicenseService
}

// NewMockLicenseService creates a new mock instance
func NewMockLicenseService(ctrl *gomock.Controller) *MockLicenseService {
	mock := &MockLicenseService{ctrl: ctrl}
	mock.recorder = &MockLicenseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLicenseService) EXPECT() *MockLicenseServiceMockRecorder {
	return m.recorder
}

// CheckLicense mocks base method
func (m *MockLicenseService) CheckLicense() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLicense")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckLicense indicates an expected call of CheckLicense
func (mr *MockLicenseServiceMockRecorder) CheckLicense() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLicense", reflect.TypeOf((*MockLicenseService)(nil).CheckLicense))
}

// Close mocks base method
func (m *MockLicenseService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockLicenseServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLicenseService)(nil).Close))
}

// ProtectCode mocks base method
func (m *MockLicenseService) ProtectCode() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtectCode")
	ret0, _ := ret[0].(error)
	return ret0
}

// ProtectCode indicates an expected call of ProtectCode
func (mr *MockLicenseServiceMockRecorder) ProtectCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtectCode", reflect.TypeOf((*MockLicenseService)(nil).ProtectCode))
}
