// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/baetyl/baetyl-cloud/v2/service (interfaces: SysConfigService)

// Package service is a generated GoMock package.
package service

import (
	models "github.com/baetyl/baetyl-cloud/v2/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSysConfigService is a mock of SysConfigService interface
type MockSysConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockSysConfigServiceMockRecorder
}

// MockSysConfigServiceMockRecorder is the mock recorder for MockSysConfigService
type MockSysConfigServiceMockRecorder struct {
	mock *MockSysConfigService
}

// NewMockSysConfigService creates a new mock instance
func NewMockSysConfigService(ctrl *gomock.Controller) *MockSysConfigService {
	mock := &MockSysConfigService{ctrl: ctrl}
	mock.recorder = &MockSysConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSysConfigService) EXPECT() *MockSysConfigServiceMockRecorder {
	return m.recorder
}

// GetSysConfig mocks base method
func (m *MockSysConfigService) GetSysConfig(arg0, arg1 string) (*models.SysConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSysConfig", arg0, arg1)
	ret0, _ := ret[0].(*models.SysConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSysConfig indicates an expected call of GetSysConfig
func (mr *MockSysConfigServiceMockRecorder) GetSysConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSysConfig", reflect.TypeOf((*MockSysConfigService)(nil).GetSysConfig), arg0, arg1)
}

// ListSysConfigAll mocks base method
func (m *MockSysConfigService) ListSysConfigAll(arg0 string) ([]models.SysConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSysConfigAll", arg0)
	ret0, _ := ret[0].([]models.SysConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSysConfigAll indicates an expected call of ListSysConfigAll
func (mr *MockSysConfigServiceMockRecorder) ListSysConfigAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSysConfigAll", reflect.TypeOf((*MockSysConfigService)(nil).ListSysConfigAll), arg0)
}
