apiVersion: v1
kind: Service
metadata:
  name: {{ include "baetyl-cloud.fullname" . }}
  labels:
    {{- include "baetyl-cloud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "baetyl-cloud.selectorLabels" . | nindent 4 }}
