/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/baetyl/baetyl-cloud/v2/plugin/kube/apis/cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeDesires implements NodeDesireInterface
type FakeNodeDesires struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var nodedesiresResource = schema.GroupVersionResource{Group: "cloud.baetyl.io", Version: "v1alpha1", Resource: "nodedesires"}

var nodedesiresKind = schema.GroupVersionKind{Group: "cloud.baetyl.io", Version: "v1alpha1", Kind: "NodeDesire"}

// Get takes name of the nodeDesire, and returns the corresponding nodeDesire object, and an error if there is any.
func (c *FakeNodeDesires) Get(name string, options v1.GetOptions) (result *v1alpha1.NodeDesire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodedesiresResource, c.ns, name), &v1alpha1.NodeDesire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDesire), err
}

// List takes label and field selectors, and returns the list of NodeDesires that match those selectors.
func (c *FakeNodeDesires) List(opts v1.ListOptions) (result *v1alpha1.NodeDesireList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodedesiresResource, nodedesiresKind, c.ns, opts), &v1alpha1.NodeDesireList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeDesireList{ListMeta: obj.(*v1alpha1.NodeDesireList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeDesireList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeDesires.
func (c *FakeNodeDesires) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodedesiresResource, c.ns, opts))

}

// Create takes the representation of a nodeDesire and creates it.  Returns the server's representation of the nodeDesire, and an error, if there is any.
func (c *FakeNodeDesires) Create(nodeDesire *v1alpha1.NodeDesire) (result *v1alpha1.NodeDesire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodedesiresResource, c.ns, nodeDesire), &v1alpha1.NodeDesire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDesire), err
}

// Update takes the representation of a nodeDesire and updates it. Returns the server's representation of the nodeDesire, and an error, if there is any.
func (c *FakeNodeDesires) Update(nodeDesire *v1alpha1.NodeDesire) (result *v1alpha1.NodeDesire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodedesiresResource, c.ns, nodeDesire), &v1alpha1.NodeDesire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDesire), err
}

// Delete takes name of the nodeDesire and deletes it. Returns an error if one occurs.
func (c *FakeNodeDesires) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodedesiresResource, c.ns, name), &v1alpha1.NodeDesire{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeDesires) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodedesiresResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeDesireList{})
	return err
}

// Patch applies the patch and returns the patched nodeDesire.
func (c *FakeNodeDesires) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NodeDesire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedesiresResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeDesire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDesire), err
}
