// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/baetyl/baetyl-cloud/v2/plugin/kube/client/clientset/versioned/typed/cloud/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCloudV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCloudV1alpha1) Applications(namespace string) v1alpha1.ApplicationInterface {
	return &FakeApplications{c, namespace}
}

func (c *FakeCloudV1alpha1) Configurations(namespace string) v1alpha1.ConfigurationInterface {
	return &FakeConfigurations{c, namespace}
}

func (c *FakeCloudV1alpha1) Nodes(namespace string) v1alpha1.NodeInterface {
	return &FakeNodes{c, namespace}
}

func (c *FakeCloudV1alpha1) NodeDesires(namespace string) v1alpha1.NodeDesireInterface {
	return &FakeNodeDesires{c, namespace}
}

func (c *FakeCloudV1alpha1) NodeReports(namespace string) v1alpha1.NodeReportInterface {
	return &FakeNodeReports{c, namespace}
}

func (c *FakeCloudV1alpha1) Secrets(namespace string) v1alpha1.SecretInterface {
	return &FakeSecrets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCloudV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
