// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/baetyl/baetyl-cloud/v2/plugin/kube/apis/cloud/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeReports implements NodeReportInterface
type FakeNodeReports struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var nodereportsResource = schema.GroupVersionResource{Group: "cloud.baetyl.io", Version: "v1alpha1", Resource: "nodereports"}

var nodereportsKind = schema.GroupVersionKind{Group: "cloud.baetyl.io", Version: "v1alpha1", Kind: "NodeReport"}

// Get takes name of the nodeReport, and returns the corresponding nodeReport object, and an error if there is any.
func (c *FakeNodeReports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodereportsResource, c.ns, name), &v1alpha1.NodeReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeReport), err
}

// List takes label and field selectors, and returns the list of NodeReports that match those selectors.
func (c *FakeNodeReports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeReportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodereportsResource, nodereportsKind, c.ns, opts), &v1alpha1.NodeReportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeReportList{ListMeta: obj.(*v1alpha1.NodeReportList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeReportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeReports.
func (c *FakeNodeReports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodereportsResource, c.ns, opts))

}

// Create takes the representation of a nodeReport and creates it.  Returns the server's representation of the nodeReport, and an error, if there is any.
func (c *FakeNodeReports) Create(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.CreateOptions) (result *v1alpha1.NodeReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodereportsResource, c.ns, nodeReport), &v1alpha1.NodeReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeReport), err
}

// Update takes the representation of a nodeReport and updates it. Returns the server's representation of the nodeReport, and an error, if there is any.
func (c *FakeNodeReports) Update(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.UpdateOptions) (result *v1alpha1.NodeReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodereportsResource, c.ns, nodeReport), &v1alpha1.NodeReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeReport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeReports) UpdateStatus(ctx context.Context, nodeReport *v1alpha1.NodeReport, opts v1.UpdateOptions) (*v1alpha1.NodeReport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodereportsResource, "status", c.ns, nodeReport), &v1alpha1.NodeReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeReport), err
}

// Delete takes name of the nodeReport and deletes it. Returns an error if one occurs.
func (c *FakeNodeReports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nodereportsResource, c.ns, name, opts), &v1alpha1.NodeReport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeReports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodereportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeReportList{})
	return err
}

// Patch applies the patch and returns the patched nodeReport.
func (c *FakeNodeReports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodereportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeReport), err
}
