nodeServer:
  port: ":9005"
  ca: "/etc/certs/client_ca.crt"
  cert: "/etc/certs/server.crt"
  key: "/etc/certs/server.key"

activeServer:
  port: ":9003"
  ca: "/etc/certs/server_ca.crt"
  cert: "/etc/certs/server.crt"
  key: "/etc/certs/server.key"

adminServer:
  port: ":9004"

plugin:
  modelStorage: "kubernetes"
  databaseStorage: "database"

kubernetes:
  inCluster: true

database:
  type: "mysql"
  url: "root:secretpassword@(mariadb:3306)/baetyl_cloud?charset=utf8&parseTime=true"
  
defaultpki:
  rootCAFile: "/etc/certs/client_ca.crt"
  rootCAKeyFile: "/etc/certs/client_ca.key"
  rootCertId : "98ec3bc552f0478298aa1c6702a95427"
  persistent:
    kind: "database"
    database:
      type: "mysql"
      url: "root:secretpassword@(mariadb:3306)/baetyl_cloud?charset=utf8&parseTime=true"

defaultauth:
  keyFile: "/etc/baetyl/token.key"

logger:
  level: debug