context:
  ginMode: "debug"

database:
  type: "mysql"
  url: "root:12345678@(host.docker.internal:3306)/baetyl_cloud?charset=utf8&parseTime=true"

kubernetes:
  inCluster: false
  configPath: "/etc/baetyl/k8s.yml"

nodeServer:
  port: ":9005"
  ca: "/etc/certs/client_ca.crt"
  cert: "/etc/certs/server.crt"
  key: "/etc/certs/server.key"

activeServer:
  port: ":9003"
  ca: "/etc/certs/server_ca.crt"
  cert: "/etc/certs/server.crt"
  key: "/etc/certs/server.key"

adminServer:
  port: ":9004"

plugin:
  modelStorage: "kubernetes"
  databaseStorage: "database"
  fileStorage: "awss3"

logger:
  level: debug
  encoding: console

awss3:
  endpoint: http://127.0.0.1:9000
  ak: minioadmin
  sk: minioadmin
  region: gz
  bucket: default
  expiration: 24h

defaultpki:
  rootCAFile: "/etc/certs/client_ca.crt"
  rootCAKeyFile: "/etc/certs/client_ca.key"
  persistent:
    kind: "database"
    database:
      type: "mysql"
      url: "root:12345678@(host.docker.internal:3306)/baetyl_cloud?charset=utf8&parseTime=true"

defaultauth:
  namespace: "default"
  keyFile: "/etc/baetyl/token.key"

resource:
  baetylBatchBucket: default
