apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFU1TXpjM05qUTJOakFlRncweU1EQTNNRE14TVRReE1EWmFGdzB6TURBM01ERXhNVFF4TURaYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFU1TXpjM05qUTJOakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk90M3RCNFlZWm5CN1J4aEU5ak5QSUcrT2xrNFBNRFg3VEVKbC9UcTJXbUYKYk5XN2NYOTUyblNNbG4xOG1GRmtpc0JudjZqbHRnYUxmR2Q1NExYcklDcWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUJMTWlncEo4NmprCkNUczFsU0tramdEZUZLcVZDK2wvUkFIZVJ4a3QxZkhHQWlFQWhPTi9IQ21DSzNISnBlRGliYXJTNnFBWVFLVFkKU0hmdHoyMklSTnVvWFBnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://192.168.64.3:6443
    name: default
contexts:
  - context:
      cluster: default
      user: default
    name: default
current-context: default
kind: Config
preferences: {}
users:
  - name: default
    user:
      password: 44b8871680e795ff31df4ea321f35ade
      username: admin